### ISSUE TITLE
Unable to run tutorial4.exe

### ISSUE THREAD

**Issue by tony11306** [allenlin316/OpenGL#1]
![image](https://user-images.githubusercontent.com/50052865/183938294-8b1d8120-10d1-4bfe-875b-c1b5cdb102f8.png)

**Comment by allenlin316** [comment]
Thanks for notice! I'm fixing this rn.

**Comment by allenlin316** [comment]
I just reuploaded the release file. Please try again

**Comment by tony11306** [comment]
All good now :)
